spring:
  application:
    name: mini-project
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:23306/mini_project_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: mini-id
    password: mini-pw
    hikari:
    maximum-pool-size: 60

  jpa:
    hibernate:
      :ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    auditing:
      enabled: true